### ISSUE TITLE
Disconnecting: Hash's MIC didn't verify

### ISSUE THREAD

**Issue by carsten-AEI** [globus/gsi-openssh#13]
Hi

on a recently upgraded Debian Stretch system with `gsi-openssh 7.1p2f` the underlying package `libglobus-gssapi-gsi4` was upgraded to 12.5-1, Matthias Ellert's/Debian's changelog is here  http://metadata.ftp-master.debian.org/changelogs//main/g/globus-gssapi-gsi/globus-gssapi-gsi_12.5-1_changelog

After the upgrade gsissh terminates with `Disconnecting: Hash's MIC didn't verify` which can be cured if `BACKWARD_COMPATIBLE_MIC=true` is set in `/etc/grid-security/gsi.conf`.

As this error also made it to openssh "proper" (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=817870) I hope/assume a proper fix will be coming to gsi-openssh sooner or later as openssh 7.2p2-2 seems to have a fi xfor that.

(I hope this does make any sense to you).

Cheers

Carsten

Disclaimer: I have used a recompiled your released version of gsi-openssh Debian packages not the original package you provide (we can go into the reasons for that but mostly it's just to have the same version strings of various packages in our repo).

**Comment by drshawnkwang** [comment]
I wanted to add that I just ran into this too, and to clarify the temporary fix is to edit  `/etc/grid-security/gsi.conf`, and set `BACKWARD_COMPATIBLE_MIC=true` on the client.

**Comment by ysvenkat** [comment]
GSI-OpenSSH 7.1p2g includes support for auto-negotiation of old and new MICs:
https://github.com/globus/gsi-openssh/releases/tag/7.1p2g
