### ISSUE TITLE
X11 forwarding fails on MacOS

### ISSUE THREAD

**Issue by jbasney** [globus/gsi-openssh#15]
http://lists.globus.org/pipermail/gt-user/2016-October/010938.html

> On Macos 10.11.6 El Capitan ssh or gsissh -X or -Y are broken for X forwarding after installing globus.
> I have the latest globus installed 
> globus-version 
> 6.0.1470089956
> gsissh -V
> OpenSSH_7.1p2-hpn14v10 GSI_GSSAPI_20160606 GSI, OpenSSL 1.0.2h  3 May 2016

Wenji Wu (FNAL) reports a similar problem.

https://bugzilla.mcs.anl.gov/globus/show_bug.cgi?id=6408 has some details on the last time we had a problem with X11 on MacOS.

**Comment by ysvenkat** [comment]
This should be fixed by the below commit, which is a port of the macports launchd.patch for OpenSSH. This will be a part of the next release of GSI-OpenSSH.

https://github.com/globus/gsi-openssh/commit/b8323bfcc1867e10c150b2ec5912bc6c883dfd6d

**Comment by ysvenkat** [comment]
Fix available in: https://github.com/globus/gsi-openssh/releases/tag/7.1p2g

**Comment by jbasney** [comment]
Related to https://github.com/openssh/openssh-portable/pull/59
