### ISSUE TITLE
Bad if statement scope at line 1579 in sftp-server.c

### ISSUE THREAD

**Issue by davidcarver** [globus/gsi-openssh#16]
Bad if statement scope  at line 1579 in sftp-server.c.   If the NERSC_MOD is defined then the if statement's scope only include the s_audit statement, causing bogus "Error: Unknown messages" in system logs.

1579-           if (handlers[i].handler == NULL)
1580-#ifdef NERSC_MOD
1581-           s_audit("sftp_process_unknown_3", "count=%i int=%d uristring=%d",
1582-                   get_client_session_id(), (int)getppid(), type);
1583-                   error("Unknown message %u", type);
1584-#else
1585-                   error("Unknown message %u", type);
1586-#endif

should be something like

1579-           if (handlers[i].handler == NULL)
1580-#ifdef NERSC_MOD
1581-           {
1582-           s_audit("sftp_process_unknown_3", "count=%i int=%d uristring=%d",
1583-                   get_client_session_id(), (int)getppid(), type);   
1584-                error("Unknown message %u", type);
1585-           }
1586-#else
1587-                   error("Unknown message %u", type);
1588-#endif

**Comment by davidcarver** [comment]
By the way, the if statement scope problem was corrected in https://github.com/set-element/openssh-hpn-isshd/blob/master/sftp-server.c by removing the s_audit statement.

**Comment by ysvenkat** [comment]
The current branch on set-element/openssh-hpn-isshd is "isshd" which still has the bug. This has been fixed in gsi-openssh (fix will be part of the next release) and a pull request has been submitted to ISSHD:

https://github.com/set-element/openssh-hpn-isshd/pull/5

Thanks for reporting it.
