### ISSUE TITLE
Merge NERSCMOD updates

### ISSUE THREAD

**Issue by jbasney** [globus/gsi-openssh#7]
https://github.com/set-element/InstrumentedSSHD contains updates since I merged the 2013-06-27 nersc-isshd.patch for OpenSSH 6.2p2. We need to review the changes from NMOD_3.12 to NMOD_3.16 and pull them in to GSI-OpenSSH as appropriate.

**Comment by ysvenkat** [comment]
Merged from https://github.com/set-element/openssh-hpn-isshd into the branch ISSHD_HPN_7_1_P1 and now regularly merging updates from that repository. This issue may be closed, unless there's more to be done. Thanks.

**Comment by jbasney** [comment]
Thanks Venkat.
